apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
      - name: logging
        image: script0kid/logging-test:v0
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: logging-svc
spec:
  selector:
    app: logging
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
